### ISSUE TITLE
Create reserved memory in flash memory

### ISSUE THREAD

**Issue by Dhanasekarsiddhi** [cypresssemiconductorco/PSoC-4-BLE#20]
I am using PSOC4 BLE and I want to store some data(like device name, MAC Address ) in flash memory and retrieve it. I would be thankful if someone guide me in this. I desperately need a help. Please, help me as soon as  possible.

**Comment by JimTrudeau** [comment]
My apologies that it appears no one has addressed this. I am fixing that problem.

I am going to assume that this is no longer an issue for you - either because you found an answer elsewhere, or perhaps you gave up. So I'm going to close your issues at this time. By all means feel free to comment, and I'll do my best to address any questions or issues.

Jim
