### ISSUE TITLE
How to program sflash using Miniprog

### ISSUE THREAD

**Issue by Dhanasekarsiddhi** [cypresssemiconductorco/PSoC-4-BLE#21]
I want to give unique user configurable address to my Psoc4 BLE(MAC address).I read that we can do it by Miniprog to program it in flash. I connected my kit using USB cable and tried to program by executing Miniprog(C:\Program Files (x86)\Cypress\Programmer\Examples\Misc\PSoC4-BLE-SFLASH-Update\Executable\PSoC4-BLE-SFLASH-Update) but it showing "No any Minipro3 is conneted to USB. Please connect only one Miniprog3 to this application" and   Can any one guide me on that, please

**Comment by JimTrudeau** [comment]
My apologies that it appears no one has addressed this. I am fixing that problem.

I am going to assume that this is no longer an issue for you - either because you found an answer elsewhere, or perhaps you gave up. So I'm going to close your issues at this time. By all means feel free to comment, and I'll do my best to address any questions or issues.

Jim
