### ISSUE TITLE
How to read connected peer device address

### ISSUE THREAD

**Issue by Dhanasekarsiddhi** [cypresssemiconductorco/PSoC-4-BLE#22]
I tried to get the address using  CyBle_GapGetPeerBdAddr() but I confused about the arguments to pass and its declaration. Can any one help me with this, please

**Comment by JimTrudeau** [comment]
My apologies that it appears no one has addressed this. I am fixing that problem.

I am going to assume that this is no longer an issue for you - either because you found an answer elsewhere, or perhaps you gave up. So I'm going to close your issues at this time. By all means feel free to comment, and I'll do my best to address any questions or issues.

Jim
