### ISSUE TITLE
Day 050 Eddystone data can configurable by android app 

### ISSUE THREAD

**Issue by koustubhemprotek** [cypresssemiconductorco/PSoC-4-BLE#23]
Hello,
I am working on Beacon Eddystone protocol with PSOC4 BLE, So i refer Day 050 Eddystone project and run it successfully. 
Now i want to make data (Eddystone UID, URL, EID etc)configurable by an android phone, so i take sample data read- write example and generate different characteristics under one service, and read write data using CY smart application.
Now I need that data enter by device broadcast in eddystone standard format, So can i get any sample code  for it which can configure data of eddystone beacon  using android application.
Thank You.

**Comment by JimTrudeau** [comment]
My apologies that it appears no one has addressed this. I am fixing that problem.

I am going to assume that this is no longer an issue for you - either because you found an answer elsewhere, or perhaps you gave up. So I'm going to close your issues at this time. By all means feel free to comment, and I'll do my best to address any questions or issues.

Jim
